--- # Poggit-CI Manifest
build-by-default: true
branches:
- master
projects:
  QueryServerCore:
    type: library
    path: ""
  QueryServer:
    path: ""
    libs:
      - src: NhanAZ-Libraries/QueryServer/QueryServerCore
        version: ^0.0.3
...
