--- # Poggit-CI Manifest
build-by-default: true
branches:
- master
projects:
  QueryServer:
    path: ""
    libs: []
  QueryConsumerExample:
    path: examples/QueryConsumer
    depend:
      - QueryServer
...
